name: Verify Bash Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  enforce-all-checks:
    name: Enforce all checks
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: Enforce all checks

